### ISSUE TITLE
Manage and reconfigure replica set options don't do anything? 

### ISSUE THREAD

**Issue by andrew-vant** [saltstack-formulas/mongodb-formula#14]
I'm trying to deploy some mongodb boxes and have them set up a replica set as part of the deployment. It looks like the manage/reconfigure replica set options in pillar.example are intended for that, but as far as I can tell they don't do anything. 

Is this a missing feature or am I doing something wrong?

**Comment by bogdanr** [comment]
It is clearly not implemented.

**Comment by vutny** [comment]
In current implementation you're able just to specify any configuration parameter recognized by MongoDB >=2.6 in `mongodb:mongod_settings` Pillar dictionary. But there are no special example of how to configure replication in the formula.

**Comment by andrew-vant** [comment]
Coming back to this a few years later, it's possible to configure the parameter, but it's done weirdly. It [looks for settings:replSet](https://github.com/saltstack-formulas/mongodb-formula/blob/5dfc05a7cde8b8149cd86c450997352227e8e304/mongodb/files/mongodb.conf.jinja#L42) when deciding whether to configure the relevant option, but takes the actual value from replica_set:name.

Appears to have been changed in #36 / 0ed0ad5, and might have been intended for backwards compatibility, I'm not sure.
