### ISSUE TITLE
Conflicting logrotate scripts

### ISSUE THREAD

**Issue by hackel** [saltstack-formulas/mongodb-formula#17]
This formula installs a script to /etc/logrotate.d/mongodb, but doesn't disable the one that comes with the package, /etc/logrotate.d/mongodb-server. This causes cron to spit out duplicate log entry errors every time it runs.  This logrotate script only exists in the standard Ubuntu package, mongodb-server (2.4.9-1ubuntu2), not in mongodb-org from their PPA.

**Comment by gravyboat** [comment]
Hmm, might be good to do a check on the ppa to determine which one is being used, and adjust the name of the managed file appropriately. I'm not extremely familiar with mongo so I don't know if this would be an issue, but that's how I would solve it. @hackel If you feel comfortable proposing a solution and making a PR please do!

**Comment by hackel** [comment]
I would just make the installation of the logrotate.d script dependent on the use_ppa pillar.  It's really strange that the mongodb package doesn't include one already.  I'm still pretty new to Salt, but I could try to do a PR.  I've already made several local customizations to make the mongodb 3.0 packages work better with Ubuntu 14.04.

**Comment by gravyboat** [comment]
@hackel If you feel comfortable with it I'd say go for it! I can't promise any sort of traction unfortunately.

**Comment by abednarik** [comment]
Just send a PR to probably workaround this issue.

**Comment by gravyboat** [comment]
@hackel I merged @abednarik's PR for now, if you have other ideas on how you'd like to solve this or don't believe it solves the problem entirely feel free to make a PR.
