### ISSUE TITLE
Need to restore ability to set version

### ISSUE THREAD

**Issue by hackel** [saltstack-formulas/mongodb-formula#28]
We don't need to pin to a specific (patch) version, but at least to a minor version that matches the URL of the deb repo.  e.g. "3.0", "3.2", etc. == ''http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2".  I think this should be a really easy change.

Inexplicably, they have included RC versions in their "stable" repo: http://repo.mongodb.org/apt/ubuntu/dists/trusty/mongodb-org/stable/multiverse/binary-amd64/Packages shows Version: 3.2.0~rc2~143~gdeaf4af (they have since added the final 3.2.0).  I definitely want to be able to check out any potential breaking changes before upgrading to a new (even minor) version.

**Comment by gravyboat** [comment]
If you want to add that in to the install with a default (of latest preferably) as well as a version line in the pillar to set it I would be happy to merge it.
