### ISSUE TITLE
Service control files are not installed on CentOS 6.4

### ISSUE THREAD

**Issue by philipsd6** [saltstack-formulas/mongodb-formula#3]
Known issue:

https://jira.mongodb.org/browse/SERVER-7285

**Comment by vutny** [comment]
@philipsd6 Hm, Mongo upstream issue was fixed only a month ago.
I think this issue could be closed. Thanks!

**Comment by philipsd6** [comment]
I can't confirm, as I'm not using Salt anymore, but I'll close anyway.
