### ISSUE TITLE
mongos not using mdb.version

### ISSUE THREAD

**Issue by smarmie** [saltstack-formulas/mongodb-formula#40]
While in init.sls the repo is defined as 
`- name: deb http://repo.mongodb.org/apt/{{ os }} {{ code }}/mongodb-org/{{ mdb.version }} {{ mdb.repo_component }}
`
in mongos.sls it's
`- name: deb http://repo.mongodb.org/apt/{{ os }} {{ code }}/mongodb-org/stable multiverse
`
And it seems repo.mongodb.org is not using "stable" (anymore):
http://repo.mongodb.org/apt/debian/dists/jessie/mongodb-org/
3.2
3.3
development
testing

**Comment by sumeetisp** [comment]
Is this issue resolved. I tried defining version in the pillars but it did not work. I also modified the defaults.yaml still it is somehow getting "stable" as the version

**Comment by gravyboat** [comment]
@sumeetisp I have no idea whether this is resolved or not, I stepped down from maintaining these about 6 months ago, sorry. Looks like there were a few PRs but doesn't appear to have been fixed.

**Comment by noelmcloughlin** [comment]
Resolved in #51
