### ISSUE TITLE
mongodb_db_path fights with mongo over group ownership

### ISSUE THREAD

**Issue by andrew-vant** [saltstack-formulas/mongodb-formula#50]
init.sls/mongodb_db_path enforces user and group ownership on the /var/lib/mongodb directory.

When mongodb restarts, it assigns group ownership of the files under /var/lib/mongodb/journal to nogroup. 

This makes for confusing output. Any time the service restarts, the next state run will report an irrelevant change.

(platform: ubuntu 16.04. Not sure how far this generalizes)

**Comment by noelmcloughlin** [comment]
This should be resolved in #51 . thanks.
