### ISSUE TITLE
problem installing on debian stretch

### ISSUE THREAD

**Issue by zwiebelspaetzle** [saltstack-formulas/mongodb-formula#52]
I get the following error in `mongodb server package installed`:
`The value 'deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/debian stretch/mongodb-org/4.0 main' is invalid for APT::Default-Release as such a release is not available in the sources`

When I manually create the list file per https://docs.mongodb.com/manual/tutorial/install-mongodb-on-debian/, it installs.

**Comment by mipapo** [comment]
Seems in mongodb/oscdoemap.yaml the " [ arch=amd64,arm64 ] " is too much. It's the only difference between the value you mentioned and the value which is mentioned at the mongodb docs
