### ISSUE TITLE
Various issues encountered when implementing `semantic-release`

### ISSUE THREAD

**Issue by myii** [saltstack-formulas/mongodb-formula#74]
Implemented `semantic-release` in #73.  Came across a number of issues when rolling that out.  Collecting them here for future reference.

---

https://travis-ci.org/myii/mongodb-formula/builds/618386706

* While I managed to get the Debian-based platforms working, all of the rest are failing badly.

---

Will need a better way to deal with version numbers and keys:

* Debian-8: 4.0
* The rest: 4.2

---

Installation and keys (per version):

* https://docs.mongodb.com/master/administration/install-on-linux/
* https://keyserver.ubuntu.com/pks/lookup?search=mongodb&fingerprint=on&op=index

---

Compass download and installation:

* https://www.mongodb.com/download-center/compass?jmp=docs
* https://docs.mongodb.com/compass/master/install/

---

CC: @noelmcloughlin.

**Comment by daks** [comment]
About the version number: is it absolutely required? Can't we imagine to just use the distro version, or an upstream repo, but without a specific version?

If this is not posible, we will need to have different pillar files by OS.

**Comment by myii** [comment]
> About the version number: is it absolutely required? Can't we imagine to just use the distro version, or an upstream repo, but without a specific version?

It doesn't look possible for the upstream repo.

https://docs.mongodb.com/master/administration/install-on-linux/

* If you follow through these docs (Antora, by the way!) and select a version from the top-left corner when you're on a page, you'll see that the repos are configured by version.

**Comment by noelmcloughlin** [comment]
#83
