### ISSUE TITLE
[BUG] Failed to start mongos.service: Unit mongos.service not found.

### ISSUE THREAD

**Issue by myii** [saltstack-formulas/mongodb-formula#81]
CC: @noelmcloughlin.  Note that we have `3000.3` images now so you may need to pull the latest changes first locally.

---

### Formula commit hash / release tag

1cd3b2c

### Versions reports (master & minion)

N/a.

### Pillar / config used

As provided in `kitchen.yml`.

---

### Describe the bug

All instances failing after the merge of #79:

* Main build: https://travis-ci.com/github/saltstack-formulas/mongodb-formula/builds/166031392
* Specific error: https://travis-ci.com/github/saltstack-formulas/mongodb-formula/jobs/334027550#L3025-L3032

```salt
                 ID: mongodb server mongos service running
           Function: service.running
               Name: mongos
             Result: False
            Comment: Failed to start mongos.service: Unit mongos.service not found.
            Started: 14:25:41.181355
           Duration: 133.196 ms
            Changes: 
```

### Steps to reproduce the bug

Run Travis for that commit or even latest.

### Expected behaviour

All should be passing, as they were before:

* Last passing build: https://travis-ci.com/github/saltstack-formulas/mongodb-formula/builds/164321089
* Specific state: https://travis-ci.com/github/saltstack-formulas/mongodb-formula/jobs/328996717#L2894-L2904

```salt
                 ID: mongodb server mongos service running
           Function: service.running
               Name: mongos
             Result: True
            Comment: Service mongos has been enabled, and is running
            Started: 20:11:57.614548
           Duration: 455.365 ms
            Changes:   
              ----------
              mongos:
                  True
```

**Comment by noelmcloughlin** [comment]
#83
